### ISSUE TITLE
Font size change when clicking on link text

### ISSUE THREAD

**Issue by CMSworker** [contao-components/tinymce4#1]
When there is a text link inside the editor and you click the linked text (to set the cursor inside the link text) the font size of the link is changing (getting smaller).

![screenshot](https://user-images.githubusercontent.com/31544192/31297073-e3222840-aae4-11e7-8dd7-318082722a5f.jpg)

(Screenshot is taken from the [Contao Demo Website Backend](https://demo.contao.org/contao) )

Could this be a problem of the contao skin css for the editor?

**Comment by leofeyer** [comment]
Behoben in 40933994137ae78f88f4f3c336bb80fa81f33d7d.
