### ISSUE TITLE
TinyMCE 6

### ISSUE THREAD

**Issue by de-es** [contao-components/tinymce4#4]
Update to TinyMCE 6 for Contao 5.

I can provide a pull request if desired.

**Comment by leofeyer** [comment]
You cannot provide a PR because I‘m using a custom TinyMCE builder to build the package. But you could outline the necessary changes, so I don‘t have to find them myself. 😄

**Comment by leofeyer** [comment]
I have added TinyMCE version 6.0.0 and 6.0.1. The accompanying PR is here: https://github.com/contao/contao/pull/4537

**Comment by de-es** [comment]
Seems I have been to slow. :laughing: Thank you for the update. :+1:
