### ISSUE TITLE
Help plugin

### ISSUE THREAD

**Issue by de-es** [contao-components/tinymce4#8]
Es kommt seitens der Redakteure öfter die Frage nach den Tastenkürzeln im TinyMCE. Auch wenn sie den Weg über den Help-Wizard bis zur tiny.cloud finden, ist für die nicht englisch sprechenden Redakteure spätestens hier der Weg zuende.

Daher die Bitte, auch das Help-Plugin direkt mit auszuliefern.

**Comment by leofeyer** [comment]
Added in version 6.8.5.1 and 7.5.1.1.
